### ISSUE TITLE
NETWORK_ERROR when set Filters

### ISSUE THREAD

**Issue by carles-mallafre** [googlesamples/android-play-places#6] opened 2015-04-07 17:57 UTC
```
Collection<Integer> filterTypes = new ArrayList<Integer>();
filterTypes.add(Place.TYPE_LOCALITY);
filterTypes.add(Place.TYPE_GEOCODE);
filterTypes.add(Place.TYPE_POLITICAL);
AutocompleteFilter filter = AutocompleteFilter.create(filterTypes);

AutocompleteFilter filter2 = AutocompleteFilter.create(PlaceTypes.ALL);

result = Places.GeoDataApi.getAutocompletePredictions(mGoogleApiClient, constraint.toString(),
                        mBounds, filter);
AutocompletePredictionBuffer buffer = result.await(10, TimeUnit.SECONDS);
```

I'm trying to set filters to get only places of type "(cities)" but any time I try to set a filter I got NETWORK_ERROR on the buffer.getStatus()

This is weird because no matter if I send a filter with all the possible types of places with:  AutocompleteFilter.create(PlaceTypes.ALL); I got this NETWORK_ERROR...

It only works when I pass the parameter as null directly or: AutocompleteFilter filter = null;

Are you sure filters are working? because there's a lack of documentation and in the examples always they filters are null.

Thanks

**Comment by asmenter15** [comment] 2015-04-14 23:10
I am also having this issue, the only time I get a response that is not NETWORK_ERROR is when i put AutoCompleteFilter as null. As far as I am concerned the only workaround at this point is to use the WebService API.

**Comment by peternagy95** [comment] 2015-04-16 02:06
I am also having that issue.

**Comment by capistrant** [comment] 2015-04-16 08:34
It appears that I am having this problem as well.

**Comment by antonrifco** [comment] 2015-04-18 14:48
I experience the same. No solution? c'mon where's googlers

**Comment by antonrifco** [comment] 2015-04-18 14:49
btw, If I only declare the Collection<Integer> filterTypes = new ArrayList<Integer>();
without adding any type, and pass it to the getAutocompletePredictions function.

it still working.

so the problem is caused by addition of any place type.

**Comment by alokedesai** [comment] 2015-04-19 15:47
+1 a fix for this relatively soon would be very nice

**Comment by jfschmakeit** [comment] 2015-05-12 06:12
Hello all,
Thank you for the reports.
I can confirm that only Geocode, Address and Establishment are supported PlaceTypes in getAutocompletePredictions. 
We will also update the error message to be more descriptive and update the documentation.

**Closed as completed by jfschmakeit** 2015-05-12 06:12 UTC

**Comment by JV-TM** [comment] 2015-06-05 05:55
Hello,
where are types specified? I could see in documentation that only geocode, address and establishement are supported. But I could not find these constants. 

filter.add(Place.TYPE_STREET_ADDRESS); doesn't work - NETWORK_ERROR

PlaceType class seems to be empty ?!?
https://developers.google.com/android/reference/com/google/android/gms/location/places/PlaceTypes

**Comment by spung** [comment] 2015-06-23 01:49
Hey @jfschmakeit, are Geocode, Address and Establishment currently available under PlaceTypes? I'm on play services location 7.5 and only see PlaceTypes.ALL, PlaceTypes.zzazO, and PlaceTypes.zzazP. If they are not, can you provide us with the integer values of them? I can't seem to find this in any documentation or examples. Thanks

**Comment by Yougin** [comment] 2015-06-23 09:22
@spung The same situation. @jfschmakeit could you please provide use with integer values?

**Comment by goolick** [comment] 2015-06-24 15:21
To echo what JV-TM said, I would like to use the address filter. Is this TYPE_STREET_ADDRESS? Because that frequently causes me to get the same NETWORK_ERROR

**Comment by spung** [comment] 2015-06-24 17:43
The javascript library seems to use strings for this.

Looking at the decompiled java class, I assume it would be one of these under ALL:

public static final Set<Integer> ALL = Collections.unmodifiableSet(new HashSet(Arrays.asList(new Integer[]{Integer.valueOf(1), Integer.valueOf(2), Integer.valueOf(3), Integer.valueOf(4), Integer.valueOf(5), Integer.valueOf(6), Integer.valueOf(7), Integer.valueOf(8), Integer.valueOf(9), Integer.valueOf(10), Integer.valueOf(11), Integer.valueOf(12), Integer.valueOf(13), Integer.valueOf(14), Integer.valueOf(15), Integer.valueOf(16), Integer.valueOf(17), Integer.valueOf(18), Integer.valueOf(19), Integer.valueOf(20), Integer.valueOf(21), Integer.valueOf(22), Integer.valueOf(23), Integer.valueOf(24), Integer.valueOf(25), Integer.valueOf(26), Integer.valueOf(27), Integer.valueOf(28), Integer.valueOf(29), Integer.valueOf(30), Integer.valueOf(31), Integer.valueOf(32), Integer.valueOf(33), Integer.valueOf(34), Integer.valueOf(35), Integer.valueOf(36), Integer.valueOf(37), Integer.valueOf(38), Integer.valueOf(39), Integer.valueOf(40), Integer.valueOf(41), Integer.valueOf(42), Integer.valueOf(43), Integer.valueOf(44), Integer.valueOf(45), Integer.valueOf(46), Integer.valueOf(47), Integer.valueOf(48), Integer.valueOf(49), Integer.valueOf(50), Integer.valueOf(51), Integer.valueOf(52), Integer.valueOf(53), Integer.valueOf(54), Integer.valueOf(55), Integer.valueOf(56), Integer.valueOf(57), Integer.valueOf(58), Integer.valueOf(59), Integer.valueOf(60), Integer.valueOf(61), Integer.valueOf(62), Integer.valueOf(63), Integer.valueOf(64), Integer.valueOf(65), Integer.valueOf(66), Integer.valueOf(67), Integer.valueOf(68), Integer.valueOf(69), Integer.valueOf(70), Integer.valueOf(71), Integer.valueOf(72), Integer.valueOf(73), Integer.valueOf(74), Integer.valueOf(75), Integer.valueOf(76), Integer.valueOf(77), Integer.valueOf(78), Integer.valueOf(79), Integer.valueOf(80), Integer.valueOf(81), Integer.valueOf(82), Integer.valueOf(83), Integer.valueOf(84), Integer.valueOf(85), Integer.valueOf(86), Integer.valueOf(87), Integer.valueOf(88), Integer.valueOf(89), Integer.valueOf(90), Integer.valueOf(91), Integer.valueOf(92), Integer.valueOf(93), Integer.valueOf(94), Integer.valueOf(95), Integer.valueOf(96), Integer.valueOf(1001), Integer.valueOf(1002), Integer.valueOf(1003), Integer.valueOf(1004), Integer.valueOf(1005), Integer.valueOf(1006), Integer.valueOf(1007), Integer.valueOf(1008), Integer.valueOf(1009), Integer.valueOf(1010), Integer.valueOf(1011), Integer.valueOf(1012), Integer.valueOf(1013), Integer.valueOf(1014), Integer.valueOf(1015), Integer.valueOf(1016), Integer.valueOf(1017), Integer.valueOf(1018), Integer.valueOf(1019), Integer.valueOf(1020), Integer.valueOf(1021), Integer.valueOf(1022), Integer.valueOf(1023), Integer.valueOf(1024), Integer.valueOf(1025), Integer.valueOf(1026), Integer.valueOf(1027), Integer.valueOf(1028), Integer.valueOf(1030)})));

**Comment by goolick** [comment] 2015-06-24 17:47
The int values are located here:

https://developers.google.com/android/reference/com/google/android/gms/location/places/Place

But I wasn't successful using the int value for STREET_ADDRESS (not that I expected it to work).

**Comment by spung** [comment] 2015-06-24 17:58
Ah I see, yes I tried the same and receive NETWORK_ERROR as well.

**Comment by jfschmakeit** [comment] 2015-06-25 01:53
Unfortunately only PLACE.TYPE_GEOCODE and PLACE.TYPE_ESTABLISHMENT are supported at the moment. There is no corresponding 'address' place type for the autocomplete API at this stage.

We are tracking this here if you'd like to follow along: https://code.google.com/p/gmaps-api-issues/issues/detail?id=8034
(You can star the issue to be notified of updates.)
In the meantime we are going to update the documentation to reflect this limitation. Thanks for the report.

**Comment by jfschmakeit** [comment] 2015-06-25 01:59
(Btw, NETWORK_ERROR is a 'generic' error, but we are working on improving error and status messages. This is being tracked here: https://code.google.com/p/gmaps-api-issues/issues/detail?id=7933 )

**Comment by vipulyaara** [comment] 2016-11-28 11:12
To everyone looking for constants under Place class, I think they are under AutocompleteFilter class. Like AutocompleteFilter.TYPE_FILTER_REGIONS, from the docs.
