### ISSUE TITLE
Place Picker App (Place Picker generic UI Widget) is working on Emulator( API version 21) but not working on Google Nexus 5 and Samsung S2 devices

### ISSUE THREAD

**Issue by getmanishmishra** [googlesamples/android-play-places#19] opened 2015-09-22 07:01 UTC
I am facing a problem in running place picker app on two devices ( Google Nexus 5 and Samsung S2).
It is working fine on Emulator with API version 21.

Place Picker app launches on device successfully but when we click on "Pick a place" link, place picker UI opens for a second but after that it is closed and the main activity is visible. It hapens every time when user will click on "Pick a place" link.

So i am not able to select/pick a place by using place picker UI widget.

Any help in resolving or finding root cause will be appreciated.

**Comment by keyboardsurfer** [comment] 2015-10-23 14:57
Please have your device connected to a development machine and run logcat.
Then perform the same task that crashes and search the log for anything suspicious that
might be related to this behavior.

**Comment by juraj-haluska** [comment] 2017-08-30 15:08
The same issue occurs on xiaomi phones. Log:

FATAL EXCEPTION: main
                                                   Process: com.google.android.gms.ui, PID: 15288
                                                   java.lang.RuntimeException: Unable to resume activity {com.google.android.gms/com.google.android.location.places.ui.placepicker.PlacePickerActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bn.o()' on a null object reference
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3136)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3167)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2514)
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5523)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bn.o()' on a null object reference
                                                       at com.google.maps.api.android.lib6.impl.cw.b(:com.google.android.gms.DynamiteModulesB:26)
                                                       at com.google.android.gms.maps.internal.v.onTransact(:com.google.android.gms.DynamiteModulesB:15)
                                                       at android.os.Binder.transact(Binder.java:387)
                                                       at brm.b(:com.google.android.gms:1)
                                                       at wae.b(:com.google.android.gms:0)
                                                       at pdh.a(:com.google.android.gms:0)
                                                       at pda.b(:com.google.android.gms:2)
                                                       at pcx.a(:com.google.android.gms:2)
                                                       at com.google.android.gms.maps.MapView.a(:com.google.android.gms:1)
                                                       at anrk.onResume(:com.google.android.gms:2)
                                                       at com.google.android.chimera.FragmentProxy.onResume(:com.google.android.gms:0)
                                                       at fy.a(:com.google.android.gms:345)
                                                       at fy.c(:com.google.android.gms:29)
                                                       at fy.a(:com.google.android.gms:210)
                                                       at fy.q(:com.google.android.gms:2)
                                                       at fy.a(:com.google.android.gms:346)
                                                       at fy.c(:com.google.android.gms:29)
                                                       at fy.a(:com.google.android.gms:210)
                                                       at fy.q(:com.google.android.gms:2)
                                                       at fo.d(:com.google.android.gms:1)
                                                       at btx.superOnResumeFragments(:com.google.android.gms:0)
                                                       at com.google.android.chimera.Activity.onResumeFragments(:com.google.android.gms:0)
                                                       at com.google.android.chimera.Activity.publicOnResumeFragments(:com.google.android.gms:0)
                                                       at btx.d(:com.google.android.gms:2)
                                                       at fo.onPostResume(:com.google.android.gms:0)
                                                       at btx.superOnPostResume(:com.google.android.gms:0)
                                                       at com.google.android.chimera.Activity.onPostResume(:com.google.android.gms:0)
                                                       at btu.onPostResume(:com.google.android.gms:0)
                                                       at com.google.android.chimera.Activity.publicOnPostResume(:com.google.android.gms:0)
                                                       at btx.onPostResume(:com.google.android.gms:2)
                                                       at android.app.Activity.performResume(Activity.java:6403)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3125)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3167) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2514) 
                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                       at java.lang.reflect.Method.invoke(Native Method)

**Comment by codingjeremy** [comment] 2019-10-04 22:27
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories

**Closed as completed by codingjeremy** 2019-10-04 22:27 UTC
